version: "3.8"

services:
    db:
        restart: always
        build: ./db/
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3
    pipline:
        build: .
        container_name: pipeline-aserbekov
        command: python pipeline.py --host 0.0.0.0 --port 8001
        volumes:
            - .:/pipelines/
        ports:
            - "8001:8001"
        depends_on:
            db:
                condition: service_healthy